version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: todo-mongo-dev # Give it a distinct name
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root # Set username (example)
      - MONGO_INITDB_ROOT_PASSWORD=example # Set password (example)
    volumes: # Optional: Make data persistent during development
      - ./mongo_data_dev:/data/db # Mount a local directory
    ports:
      # Map container port 27017 to host port 127.0.0.1:27017 (localhost only)
      - 127.0.0.1:27017:27017
    restart: unless-stopped

  # Add the Redis service below mongo
  redis:
    image: redis:alpine # Use a lightweight redis image
    container_name: todo-redis-dev # Give it a distinct name
    ports:
      # Map container port 6379 to host port 127.0.0.1:6379 (localhost only)
      # This is necessary because we will run the Node app OUTSIDE this container
      # and it needs to connect via localhost.
      - '127.0.0.1:6379:6379'
    restart: unless-stopped
    # No volumes needed for this exercise, as we only test the connection setup
# Optional: Define the volume if you used it for mongo persistence
# volumes:
#   mongo_data_dev:
